FDTN-689: Updated node base image
flowcommerce/docker pull request #58
Opened 2022-02-09 13:45 UTC by Yatharth0045

2022-02-09 14:44 UTC, RoryH commented on node/Dockerfile.node_builder12
> +    apk -v --purge del py-pip
```suggestion
    pip install --upgrade awscli
```

This command `apk -v --purge del py-pip` was removed in my latest PR... It causes a python dependency `six` to be removed which the awscli depends on at runtime.

2022-02-10 11:13 UTC, gheine commented on node/build-node_builder
> +node_image_tag = "flowdocker/node_builder%s:%s" % [node_version, node_tag]
would prefer naming this "flowdocker/node%s_builder:%s" % [node_version, node_tag]

2022-02-10 11:14 UTC, gheine commented on node/build-node_builder
> +node_image_tag = "flowdocker/node_builder%s:%s" % [node_version, node_tag]
eg node12_builder instead of node_builder12

2022-02-10 11:16 UTC, RoryH commented on node/build-node_builder
> +node_image_tag = "flowdocker/node_builder%s:%s" % [node_version, node_tag]
Yeah, I prefer @gheine 's suggestion also. 👍🏻

2022-02-11 04:39 UTC, tgamyatharth commented on node/build.go
> +	executor = executor.Add("./build-node_builder `sem-info tag latest` 16")
Just thinking to give @benwaffle  a chance to look into it once. I'll talk to him async on this.

2022-02-11 09:25 UTC, Yatharth0045 commented on node/build.go
> +	executor = executor.Add("./build-node_builder `sem-info tag latest` 16")
Updated @gheine

2022-02-11 11:10 UTC, gheine commented on node/build-node_builder
> -  if confirm("Enter 'Y' to push this image (%s) to Docker hub" % node_image_tag)
remove the confirm function from helpers.rb if it's not being used any more

2022-02-11 11:11 UTC, gheine requested changes
See above

2022-02-11 14:40 UTC, gheine approved these changes
lgtm

2022-02-14 09:42 UTC, merged