Fdtn 78
flowcommerce/docker pull request #67
Opened 2022-10-31 06:10 UTC by himanshuupadhyay101

2022-10-31 11:49 UTC, gheine commented on Jenkinsfile
> +     string(name: 'VERSION', defaultValue: 'VERSION.printable()', description: 'VERSION.printable()')
No no, delete this. You need to replace `params.SEM_INFO` below with `VERSION.printable()`

2022-10-31 11:49 UTC, gheine commented on Jenkinsfile
> +          sh "cd play && ./build-play ${params.SEM_INFO} ${params.VERSION13} && ./play/build-play-builder ${params.SEM_INFO} ${params.VERSION13}"
Also needs to be run with the jenkins-build IAM role

2022-10-31 11:51 UTC, gheine requested changes
See inline. Also all steps that build docker images need to be guarded to only run on main

2022-10-31 11:51 UTC, benwaffle reviewed
Can you add a meaningful title to the PR as well? thanks :)

2022-10-31 11:51 UTC, benwaffle commented on Jenkinsfile
>       string(name: 'VERSION13', defaultValue: '13', description: 'version')
Why are these set up as parameters? Can we just hardcode these where they are used? (e.g. line 61-66)

2022-10-31 18:48 UTC, gheine commented on Jenkinsfile
>       string(name: 'VERSION13', defaultValue: '13', description: 'version')
+1

2022-11-01 08:30 UTC, himanshuupadhyay101 commented
> 

yes, after succesfull testing of stages in this branch, i will add the condition to run only on main

2022-11-01 08:53 UTC, gheine commented on Jenkinsfile
> +    stage('Upgrade node docker image') {
node and play stages can be run in parallel

2022-11-01 08:54 UTC, gheine commented on Jenkinsfile
> +                sh "cd play && ./build-play ${VERSION.printable()} 13 && ./build-play-builder ${VERSION.printable()} 13"
please break out into multiple lines, this is hard to read

2022-11-01 08:54 UTC, gheine commented on Jenkinsfile
> +            withCredentials([string(credentialsId: "jenkins-hub-api-token", variable: 'GITHUB_TOKEN')]){
you'll also need to run with the the `jenkins-build` and install ruby

2022-11-01 18:26 UTC, gheine commented on node/helpers.rb
> + end
revert this file

2022-11-01 18:27 UTC, gheine commented on Jenkinsfile
> +                  sh "apk update && apk add ruby curl aws-cli"
move down to above line 57

2022-11-01 18:28 UTC, gheine commented on Jenkinsfile
> +                            ./build-node_builder ${VERSION.printable()} 18
not sure these multi-line sh commands work. you may either need to break them out into separate sh commands, or chain them with a `&&` at the end of each line

2022-11-01 18:29 UTC, gheine commented on play/build-play-builder
> +PROJECTS_TO_BUILD = %w(flowcommerce/experience flowcommerce/catalog flowcommerce/label flowcommerce/shopify flowcommerce/webhook flowcommerce/demandware flowcommerce/harmonization flowcommerce/tax fl
add flowcommerce/shopify-markets and flowcommerce/calculator

2022-11-02 05:38 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                            ./build-node_builder ${VERSION.printable()} 18
yeah, they work. this stage got passed earlier, so i have put condition to only trigger on main branch

2022-11-02 17:57 UTC, gheine commented on node/helpers.rb
> + end
Still needs to be reverted @himanshuupadhyay101

2022-11-02 18:14 UTC, gheine commented on Jenkinsfile
> +            when { branch 'main' }
Is this branch working? Can you temporarily disable the `main` check to verify?

2022-11-02 18:19 UTC, gheine commented on Jenkinsfile
> +                            apt-get install sbt -y
Instead of doing all this, can we use an existing version of our play-builder image to run the play build?

2022-11-02 18:19 UTC, gheine commented on Jenkinsfile
> +        containerTemplate(name: 'ubuntu', image: 'ubuntu', resourceRequestCpu: '1', resourceRequestMemory: '2Gi', command: 'cat', ttyEnabled: true)
Instead of using a vanilla ubuntu image and installing jdk and sbt, can we take an existing version of our play-builder image to build the dependencies (see my comment below)?

2022-11-03 10:35 UTC, gheine commented on Jenkinsfile
> +        containerTemplate(name: 'play-builder', image: 'flowdocker/play_builder:0.2.2-java13', resourceRequestCpu: '1', resourceRequestMemory: '2Gi', command: 'cat', ttyEnabled: true)
use `play_builder:latest-java13`

2022-11-03 10:42 UTC, gheine commented on Jenkinsfile
> +                            aws sts get-caller-identity
doesn't look like this is needed

2022-11-03 10:43 UTC, gheine commented on Jenkinsfile
> +                  sh "apk update && apk add --no-cache docker-cli"
is this needed?

2022-11-03 10:44 UTC, gheine requested changes
Few comments inline, but nearly there!!

2022-11-03 11:46 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                  sh "apk update && apk add --no-cache docker-cli"
yes, the play_builder uses alpine as base, so docker need to be installed.

2022-11-03 12:39 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                            aws sts get-caller-identity
This is needed as docker container does not contain these by default. Earlier i tried without them, it gave error. confirmed just now also. 
Removed  "aws sts get-caller-identity"

2022-11-03 12:40 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                            aws sts get-caller-identity
ruby is  required to run ruby scripts

2022-11-03 12:56 UTC, gheine commented on Jenkinsfile
> +                            apk add ruby curl aws-cli
is `aws-cli` still needed?

2022-11-03 13:17 UTC, gheine reviewed
Few more comments inline

2022-11-03 13:22 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                  sh "apk update && apk add --no-cache docker-cli"
This installs needs to be before `docker.withRegistry('https://index.docker.io/v1/', 'jenkins-dockerhub')`  statement, otherwise it will throw error

2022-11-03 14:56 UTC, gheine commented on Jenkinsfile
> +    cron(env.BRANCH_NAME == 'main' ? '0 17 * * 5' : '')
Can we do 10am GMT on Monday instead

2022-11-03 14:57 UTC, gheine commented on Jenkinsfile
>    }
Are these environment variables used anywhere? if not please remove.

2022-11-03 14:58 UTC, gheine commented on Jenkinsfile
> +                  sh "apk update && apk add --no-cache docker-cli"
👍

2022-11-03 14:59 UTC, gheine requested changes
few more minor things inline

2022-11-03 15:01 UTC, benwaffle commented on Jenkinsfile
> +                  sh "apk update && apk add --no-cache docker-cli"
You can install all of the packages on line 84

2022-11-03 15:02 UTC, benwaffle requested changes

2022-11-03 15:02 UTC, benwaffle commented on play/Dockerfile.play_builder-13
> +    echo -e "http://nl.alpinelinux.org/alpine/v3.10/main\nhttp://nl.alpinelinux.org/alpine/v3.10/community" > /etc/apk/repositories && \
Why are we doing this? The default repos should work out of the box.

2022-11-03 16:54 UTC, himanshuupadhyay101 commented on play/Dockerfile.play_builder-13
> +    echo -e "http://nl.alpinelinux.org/alpine/v3.10/main\nhttp://nl.alpinelinux.org/alpine/v3.10/community" > /etc/apk/repositories && \
I reverted this, i did this to fix one error when we were using docker alpine image container. but now it is not needed. So reverted

2022-11-03 17:25 UTC, gheine commented on Jenkinsfile
> +    // Only trigger the cron build if on main branch and 5pm friday
update the comment to reflect the cron schedule

2022-11-03 17:25 UTC, gheine commented on Jenkinsfile
> +                script{
@himanshuupadhyay101

2022-11-03 17:28 UTC, gheine approved these changes
LGTM, please address the remaining comments and merge PR

2022-11-04 05:23 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +    // Only trigger the cron build if on main branch and 5pm friday
cron was updated for 10 am got

2022-11-04 06:07 UTC, merged